version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: "thursday"
      time: "08:20"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
      - npm

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "08:20"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
      - github-actions
